# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - thor_arm_controller

  thor_arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - art1_yaw
      - art2_pitch
      - art3_pitch
      - art4_roll
      - art5_pitch
      - art6_roll